SLEEP_TIME_AFTER_CONNECT = 3.0  # in secunde
SLEEP_TIME_BETWEEN_SCREENSHOTS = 0.5  # in secunde
SLEEP_TIME_IN_MAIN_LOOP = 0.5  # in secunde
SLEEP_TIME_AFTER_APPLIED_MOVE = 3.0  # in secunde

NUM_TILES_WIDTH = 8
NUM_TILES_HEIGHT = 8

WHITE_TILE_RGB = (235, 236, 208)
WHITE_TILE_EPS = (1, 1, 1)
BLACK_TILE_RGB = (115, 149, 82)
BLACK_TILE_EPS = (1, 1, 1)

WHITE_PIECE_RGB = (249, 249, 249)
WHITE_PIECE_EPS = (50, 50, 50)
WHITE_PIECE_VARIANCE_EPS = 11
BLACK_PIECE_RGB = (92, 89, 87)
BLACK_PIECE_EPS = (50, 50, 50)
BLACK_PIECE_VARIANCE_EPS = 11

SCREENSHOT_SCALE_WIDTH = 0.25
SCREENSHOT_SCALE_HEIGHT = 0.25

INITIAL_BOARD_CONFIGURATION = 'RNBKQBNRPPPPPPPP................................pppppppprnbkqbnr'

SLEEP_TIME_WHEN_APPLYING_MOVE = 0.25  # in secunde
MOUSE_MOVE_DURATION = 0.1  # in secunde

HOST = 'localhost'
PORT = 10000  # Acest port trebuie sa coincida cu cel din aplicatie.

SLEEP_TIME_BETWEEN_CONNECTION_RETRIES = 1.0  # in secunde

STRING_SIZE_MOVE = 6
STRING_SIZE_CONFIGURATION = NUM_TILES_HEIGHT * NUM_TILES_WIDTH

START_BY_LISTENING = False

TEMPLATE_WIDTH = 32
TEMPLATE_HEIGHT = 32

NUM_WHITE_PIECES = 6
NUM_BLACK_PIECES = 6
NUM_NON_PIECES = 1

NUM_CLASSES = NUM_WHITE_PIECES + NUM_BLACK_PIECES  # + NUM_NON_PIECES

NUM_COLOR_CHANNELS = 3

FROM_PIECE_TO_LABEL = {
    'P': 0,
    'R': 1,
    'N': 2,
    'B': 3,
    'Q': 4,
    'K': 5,

    'p': 6,
    'r': 7,
    'n': 8,
    'b': 9,
    'q': 10,
    'k': 11,

    '.': 12
}

MAX_VALUE_PIXEL = 255

FROM_LABEL_TO_PIECE = {
    0: 'P',
    1: 'R',
    2: 'N',
    3: 'B',
    4: 'Q',
    5: 'K',

    6: 'p',
    7: 'r',
    8: 'n',
    9: 'b',
    10: 'q',
    11: 'k',

    12: '.'
}


NUM_REPEATS_DATASET = 100
BATCH_SIZE = 64

NUM_EPOCHS = 5
LEARNING_RATE = 0.001


NUM_ENTITIES_ON_BOARD = NUM_TILES_HEIGHT * NUM_TILES_WIDTH
CLASS_WEIGHTS = [
    NUM_ENTITIES_ON_BOARD / 8,
    NUM_ENTITIES_ON_BOARD / 2,
    NUM_ENTITIES_ON_BOARD / 2,
    NUM_ENTITIES_ON_BOARD / 2,
    NUM_ENTITIES_ON_BOARD / 1,
    NUM_ENTITIES_ON_BOARD / 1,

    NUM_ENTITIES_ON_BOARD / 8,
    NUM_ENTITIES_ON_BOARD / 2,
    NUM_ENTITIES_ON_BOARD / 2,
    NUM_ENTITIES_ON_BOARD / 2,
    NUM_ENTITIES_ON_BOARD / 1,
    NUM_ENTITIES_ON_BOARD / 1,

    # NUM_ENTITIES_ON_BOARD / 32
]

