SLEEP_TIME_AFTER_CONNECT = 3.0  # in secunde
SLEEP_TIME_BETWEEN_SCREENSHOTS = 0.5  # in secunde
SLEEP_TIME_IN_MAIN_LOOP = 0.5  # in secunde
SLEEP_TIME_AFTER_APPLIED_MOVE = 3.0  # in secunde

NUM_TILES_WIDTH = 8
NUM_TILES_HEIGHT = 8

WHITE_TILE_RGB = (235, 236, 208)
WHITE_TILE_EPS = (1, 1, 1)
BLACK_TILE_RGB = (115, 149, 82)
BLACK_TILE_EPS = (1, 1, 1)

WHITE_PIECE_RGB = (249, 249, 249)
WHITE_PIECE_EPS = (1, 1, 1)
BLACK_PIECE_RGB = (92, 89, 87)
BLACK_PIECE_EPS = (1, 1, 1)

SCREENSHOT_SCALE_WIDTH = 0.2
SCREENSHOT_SCALE_HEIGHT = 0.2

INITIAL_BOARD_CONFIGURATION = 'RNBKQBNRPPPPPPPP................................pppppppprnbkqbnr'

SLEEP_TIME_WHEN_APPLYING_MOVE = 0.25  # in secunde
MOUSE_MOVE_DURATION = 0.1  # in secunde

HOST = 'localhost'
PORT = 10000  # Acest port trebuie sa coincida cu cel din aplicatie.

SLEEP_TIME_BETWEEN_CONNECTION_RETRIES = 1.0  # in secunde

STRING_SIZE_MOVE = 6
STRING_SIZE_CONFIGURATION = NUM_TILES_HEIGHT * NUM_TILES_WIDTH

START_BY_LISTENING = False

TEMPLATE_WIDTH = 32
TEMPLATE_HEIGHT = 32

